#!/bin/bash

# Use "ip" command to get the list of network interfaces
interfaces=$(ip -o -4 addr | awk '{print $2}')

# Loop through each interface and extract IPv4 addresses
for interface in $interfaces; do
  # Filter out the loopback interface (127.0.0.1)
  if [[ $interface != "lo" ]]; then
    ipv4_address=$(ip -o -4 addr show $interface | awk '{print $4}')
    echo "Interface: $interface | IPv4 address: $ipv4_address"
  fi
done
